### ISSUE TITLE
The Android version hopes to add a Chinese Simplified interface as well  

### ISSUE THREAD

**Issue by iD2073** [bepass-org/oblivion#199] opened 2024-05-21 09:18 UTC
The Android version hopes to add a Chinese Simplified interface as well

**Comment by aintfp** [comment] 2024-05-23 12:17
中文的https://www.123pan.com/s/cvWVVv-ZX7A3.html
![Screenshot_2024-05-22-18-42-41-023_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/75429131/6980e444-f9cf-4171-a85c-6a644f4d259e)

**Comment by renshengx** [comment] 2024-05-24 03:35
The Chinese language is not supported, and the interface does not change after modifying the language. It is recommended to modify it similar to the desktop version.

**Comment by markpash** [comment] 2024-05-27 04:12
Duplicate of #162

**Closed by markpash** 2024-05-27 04:12 UTC
