### ISSUE TITLE
Add language support for Chinese (Android application)

### ISSUE THREAD

**Issue by muller2333** [bepass-org/oblivion#209] opened 2024-05-22 10:32 UTC
I have installed the Android version but the language of the interface does not support Chinese.

**Comment by aintfp** [comment] 2024-05-22 10:43
忘记在哪下载的版本，中文的
https://www.123pan.com/s/cvWVVv-ZX7A3.html
![Screenshot_2024-05-22-18-42-41-023_org bepass oblivion](https://github.com/bepass-org/oblivion/assets/75429131/77c2749a-4fcc-4564-a43f-b60952aeae72)

**Comment by renshengx** [comment] 2024-05-24 03:36
The Chinese language is not supported, and the interface does not change after modifying the language. It is recommended to modify it similar to the desktop version.

**Comment by DanielcoderX** [comment] 2024-05-25 10:29
你好，我们很高兴看到应用程序已经超出了预期的边界。在下一次更新中，我们将努力添加俄语、中文和英语。
祝你有美好的一天。

**Comment by markpash** [comment] 2024-05-27 04:12
Duplicate of #162

**Closed by markpash** 2024-05-27 04:12 UTC
