### ISSUE TITLE
unable to change psiphon location

### ISSUE THREAD

**Issue by mohammad35322** [bepass-org/oblivion#77] opened 2024-02-24 04:22 UTC
When I want to change the location of the Psiphon, after exiting the settings menu, it returns to automatic mode, and even after connecting, it does not give the location I want. Another problem is that all kinds of check ip sites don't open and this is another problem and I can't check the ip location, but these problems were not in the previous version. Please fix the problems, thank you

**Comment by mohammad35322** [comment] 2024-02-24 04:23
https://github.com/bepass-org/oblivion/assets/49150138/87b40634-6892-471e-95e6-efeb430ddb37

**Comment by HiddenCoderIR** [comment] 2024-02-24 05:56
> When I want to change the location of the Psiphon, after exiting the settings menu, it returns to automatic mode, and even after connecting, it does not give the location I want. Another problem is that all kinds of check ip sites don't open and this is another problem and I can't check the ip location, but these problems were not in the previous version. Please fix the problems, thank you

Have you tried reinstalling the app? It may need a fresh install, not an update.

P.S: Don't forget to back up your Warp license.

**Comment by mohammad35322** [comment] 2024-02-24 06:22
Yes several times but the problem still persists

**Comment by mohammad35322** [comment] 2024-02-24 06:24
It did not allow updating, I had to delete the previous version and install the new version

**Comment by HiddenCoderIR** [comment] 2024-02-24 06:57
> It did not allow updating, I had to delete the previous version and install the new version

Thank you for reporting the issue regarding the location change problem with Psiphon. We have identified the cause of this issue.

The problem arises because your device's language is not set to English. (The Persian digits in the status bar clock within the provided video clip gave us this clue). We apologize for this bug, and it will be fixed in the upcoming release.

As a temporary workaround, we suggest changing your device's language to English. This should resolve the issue with the location not being properly set.

**Closed** 2024-05-11 15:50 UTC
