### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by inattentive-nerd** [bepass-org/oblivion#181] opened 2024-05-16 20:48 UTC
It might help people living in other parts of the world who are dealing with internet censorship.

**Comment by mrjaycodes** [comment] 2024-05-17 14:39
Hi, oblivion with English translation is available on windows at:
https://github.com/mrjaycodes/OblivionDesktop

you can use it completely free.

**Comment by markpash** [comment] 2024-05-18 23:34
Duplicate of #171

**Closed by markpash** 2024-05-18 23:34 UTC
