### ISSUE TITLE
Unable to toggle the switch off

### ISSUE THREAD

**Issue by mazdakdev** [bepass-org/oblivion#128] opened 2024-04-09 06:35 UTC
It seems that the button cannot be toggled off when attempting to connect. the button can only be turned off by force stopping it through the Android system settings. This issue specifically arises when the loading animation is active.

App Version: 2
Android Version: 13

![Screenshot_2024-04-09-09-48-06-421_org.bepass.oblivion-edit.jpg](https://github.com/bepass-org/oblivion/assets/60855141/add2dfab-f924-4a73-b938-3df41e3c6f78)

**Comment by Amir2367** [comment] 2024-04-09 13:16
> It seems that the button cannot be toggled off when attempting to connect. the button can only be turned off by force stopping it through the Android system settings. This issue specifically arises when the loading animation is active.
> 
> App Version: 2 Android Version: 13
> 
> ![Screenshot_2024-04-09-09-48-06-421_org.bepass.oblivion-edit.jpg](https://private-user-images.githubusercontent.com/60855141/320743463-add2dfab-f924-4a73-b938-3df41e3c6f78.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Njg4MDYsIm5iZiI6MTcxMjY2ODUwNiwicGF0aCI6Ii82MDg1NTE0MS8zMjA3NDM0NjMtYWRkMmRmYWItZjkyNC00YTczLWI5MzgtM2RmNDFlM2M2Zjc4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEzMTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOTM5MjE2N2QxMzM5YmEzMzVkZGUyZGQ1Y2Q0YmJjZjllODEzODE1ZDhmZDIxMWEwMDc5Njg0ZTA3NzkyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PVoBnFHH8Mq6ux1Su4bzHiQ3JUB7OPryz7nCGhkGA1k)

It seems that the button cannot be toggled off when attempting to connect. the button can only be turned off by force stopping it through the Android system settings. This issue specifically arises when the loading animation is active.

> It seems that the button cannot be toggled off when attempting to connect. the button can only be turned off by force stopping it through the Android system settings. This issue specifically arises when the loading animation is active.
> 
> App Version: 2 Android Version: 13
> 
> ![Screenshot_2024-04-09-09-48-06-421_org.bepass.oblivion-edit.jpg](https://private-user-images.githubusercontent.com/60855141/320743463-add2dfab-f924-4a73-b938-3df41e3c6f78.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Njg4NTYsIm5iZiI6MTcxMjY2ODU1NiwicGF0aCI6Ii82MDg1NTE0MS8zMjA3NDM0NjMtYWRkMmRmYWItZjkyNC00YTczLWI5MzgtM2RmNDFlM2M2Zjc4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEzMTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYTY5NzA1MTk0ODViZDk2NjhjODEyMThiNWY2NWM1MWVjNzI0MWFkYmUzM2UxMGFlMGQ5MTExOGRlYzhkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lyxyAcei7RhTKiiRrVrOtqAvow5E5xPO7s55YzQmzYE)

Yes, I have the same problem.

**Comment by Amir2367** [comment] 2024-04-09 13:17
> It seems that the button cannot be toggled off when attempting to connect. the button can only be turned off by force stopping it through the Android system settings. This issue specifically arises when the loading animation is active.
> 
> App Version: 2 Android Version: 13
> 
> ![Screenshot_2024-04-09-09-48-06-421_org.bepass.oblivion-edit.jpg](https://private-user-images.githubusercontent.com/60855141/320743463-add2dfab-f924-4a73-b938-3df41e3c6f78.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2Njg5MjMsIm5iZiI6MTcxMjY2ODYyMywicGF0aCI6Ii82MDg1NTE0MS8zMjA3NDM0NjMtYWRkMmRmYWItZjkyNC00YTczLWI5MzgtM2RmNDFlM2M2Zjc4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDEzMTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YzJjZDlkMDBlNDYyZWYxMTJjODk0ODBjYjdmMTU4ODFlNTliMTJkNjg2NWY1MTRlMGIxYTQ0MWM1YzEwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UBhFczKM4ved9FoLF9XPr4Y61OhCxIXmRbP60-XX4io)

Yes, I have the same problem

**Comment by markpash** [comment] 2024-05-11 14:50
Duplicate of #147

**Closed by markpash** 2024-05-11 14:50 UTC
